[package]
name = "num-width"
version = "0.1.0"
edition = "2021"
authors = ["Patrick M. Elsen <pelsen@xfbs.net>"]
license = "MIT"
description = "Trait to determine number width"

[dependencies]
num-bigint = { version = "0.4.0", optional = true }
